platform :ios, 9

use_frameworks!

plugin 'cocoapods-keys', {
  :project => 'FTP',
  :keys => [
  	'shopifyDomain',
    'shopifyAPIKey',
    'shopifyChannelId',
    'oneSignalAPIKey'
  ]}
pod 'OneSignal'
pod 'Mobile-Buy-SDK', '~> 1.2.4'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Haneke', '~> 1.0'
pod 'Alamofire', '~> 3.0'
